name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Test app
      uses: actions/setup-node@v4
      with:
        node-version: '>=18' 
    - run: npm ci
    - run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test-ci
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t pos-fiap-fase2 .
    - run: echo "Deploy"
